import '@/styles/common.scss'
import Link from 'next/link'
import Head from 'next/head'
import {Nav} from "@/src/Nav"

//pages -> 오토라우터 제공

//pages라우터 -> (<Link>,useRouter 사용)

//css -> 글로벌/페이별 생성(module)
export default function App({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Nav />
      <Component {...pageProps} />
    </>
  )
}
